# Temporary fix to group Angular dependency updates together until dependabot supports group updates
# Inspired from: https://github.com/dependabot/dependabot-core/issues/1296#issuecomment-657438154
name: Bump Angular

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 2" # midnight on Tuesdays

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      # Update all the Angular libraries at once
      - name: Update Angular
        run: |
          npm ci
          ./node_modules/.bin/ng update @angular/cli @angular/core

      # Create a pull request if there are any changes
      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          # A PAT must be used instead of GITHUB_TOKEN to prevent recursive workflow runs
          # See https://stackoverflow.com/a/72451611
          token: ${{ secrets.PAT }}
          commit-message: Bump Angular
          title: "[AUTO] Bump Angular"
          labels: dependencies,javascript
          branch: "abhibot/angular"

      # Send an email if a PR was created (since there's no notification if the author is yourself)
      - name: Send email
        if: ${{ steps.cpr.outputs.pull-request-number }}
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address if not connection_url:
          server_address: imap.mail.yahoo.com
          # Server port, default 25:
          server_port: 465
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional (recommended): mail server username:
          username: ${{ secrets.MAIL_USERNAME }}
          # Optional (recommended) mail server password:
          password: ${{ secrets.MAIL_PASSWORD }} # app password
          # Required mail subject:
          subject: |
            "[${{ github.repository }}] [AUTO] Bump Angular (PR #${{ steps.cpr.outputs.pull-request-number }})"
          # Required recipients' addresses:
          to: achaudhuri2011@yahoo.com
          # Required sender full name (address can be skipped):
          from: abhibot[bot] # <user@example.com>
          # Optional plain body:
          body: |
            Hooray! A brand new version of Angular has been released! 🎉

            You can view, comment on, or merge this pull request online at:
            ${{ steps.cpr.outputs.pull-request-url }}
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true
